name: chat_bot
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_auth: ^5.5.4
  provider: ^6.1.2
  google_gemini: ^0.1.2
  http: ^1.3.0
  google_generative_ai: ^0.4.6
  google_fonts: ^6.2.1
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  get: ^4.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1  # ← Added here

flutter:
  uses-material-design: true

  assets:
    - assets/daek aquatic color (3).jpg
    - assets/google-logo.png
    - assets/HD-wallpaper-blueorange.jpeg
    - assets/HD-wallpaper-butterfly.jpg
    - assets/HD-wallpaper-nice-neon-blue.jpg

# ↓ flutter_launcher_icons config starts here
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/Gemini_Generated_Image_lleh78lleh78lleh.png" # Make sure this file exists
  min_sdk_android: 23
  remove_alpha_ios: true
