// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiYRpeTz7QZ9olLqwxlAXlQdI_9195TDo',
    appId: '1:1000808572543:web:e539c228bd6c42a2ce814a',
    messagingSenderId: '1000808572543',
    projectId: 'chat-ai-9a65b',
    authDomain: 'chat-ai-9a65b.firebaseapp.com',
    storageBucket: 'chat-ai-9a65b.firebasestorage.app',
    measurementId: 'G-Y04L3BWMGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl9XsbkZy6x2dCyyiDAmB5K74T7_tfAbM',
    appId: '1:1000808572543:android:aad08f1f8f5a2e9dce814a',
    messagingSenderId: '1000808572543',
    projectId: 'chat-ai-9a65b',
    storageBucket: 'chat-ai-9a65b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxfIteLeI-av3872rz34pWh65GFZjFXC4',
    appId: '1:1000808572543:ios:2237061e9a90e2bdce814a',
    messagingSenderId: '1000808572543',
    projectId: 'chat-ai-9a65b',
    storageBucket: 'chat-ai-9a65b.firebasestorage.app',
    iosBundleId: 'com.example.chatBot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxfIteLeI-av3872rz34pWh65GFZjFXC4',
    appId: '1:1000808572543:ios:2237061e9a90e2bdce814a',
    messagingSenderId: '1000808572543',
    projectId: 'chat-ai-9a65b',
    storageBucket: 'chat-ai-9a65b.firebasestorage.app',
    iosBundleId: 'com.example.chatBot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiYRpeTz7QZ9olLqwxlAXlQdI_9195TDo',
    appId: '1:1000808572543:web:64c4beeab892211ece814a',
    messagingSenderId: '1000808572543',
    projectId: 'chat-ai-9a65b',
    authDomain: 'chat-ai-9a65b.firebaseapp.com',
    storageBucket: 'chat-ai-9a65b.firebasestorage.app',
    measurementId: 'G-JMXN4113F8',
  );
}
