import 'package:chat_bot/wallpaper.dart';
import 'package:flutter/material.dart';


class Termsandconditions extends StatelessWidget {
  final String currentWallpaper;
  Termsandconditions({required this.currentWallpaper});
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      resizeToAvoidBottomInset: false,
      appBar: AppBar(title: Text('Terms and Conditions')),
      body: BackgroundContainer(
        backgroundImage: currentWallpaper,
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(16.0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                'Terms and Conditions for ChatAi',
                style: TextStyle(
                  fontSize: 15,
                  fontWeight: FontWeight.bold,
                ),
              ),
              SizedBox(height: 10),
              Text('Last Updated: May 2025'),
              SizedBox(height: 16),
              Text(
                'Welcome to ChatAi. These Terms and Conditions govern your use of our chatbot services. By accessing or using the chatbot, you acknowledge that you have read, understood, and agree to be bound by these terms. If you do not agree to these terms, please refrain from using the chatbot.',
              ),
              SizedBox(height: 16),
              Text(
                '1. Use of the Chatbot',
                style: TextStyle(fontSize: 15, fontWeight: FontWeight.bold),
              ),
              SizedBox(height: 8),
              Text(
                'The chatbot is designed to provide users with [support, information, conversation, etc.]. It is intended for lawful use only and must not be used for any malicious, harmful, or unlawful purposes. You agree not to misuse or abuse the chatbot, interfere with its operation, or attempt to gain unauthorized access to systems or data. Users must be at least [13/16/18] years old, depending on the applicable regulations in their region.',
              ),
              SizedBox(height: 16),
              Text(
                '2. No Professional Advice',
                style: TextStyle(fontSize: 15, fontWeight: FontWeight.bold),
              ),
              SizedBox(height: 8),
              Text(
                "The chatbot is not a substitute for professional advice. Any responses provided by the chatbot are for general informational purposes only. Whether the topic is medical, legal, financial, or otherwise, you should consult with a qualified professional before making any decisions based on the chatbot's responses. We do not guarantee the accuracy, completeness, or usefulness of the information it provides.",
              ),
              SizedBox(height: 16),
              Text(
                "3. Privacy and Data Collection",
                style: TextStyle(fontSize: 15, fontWeight: FontWeight.bold),
              ),
              SizedBox(height: 8),
              Text(
                "While using the chatbot, we may collect data you voluntarily provide, such as questions or feedback, to help improve the quality and accuracy of our services. This data may be stored and analyzed in compliance with our privacy policy. However, we are committed to respecting your privacy and do not sell or share your data with third parties without consent. Please avoid sharing sensitive personal information unless necessary.",
              ),
              SizedBox(height: 16),
              Text(
                "4. Intellectual Property",
                style: TextStyle(fontSize: 15, fontWeight: FontWeight.bold),
              ),
              SizedBox(height: 8),
              Text(
                "All content and responses generated by the chatbot, along with any underlying software or design, are the intellectual property of [Your Company/Name]. You may use the content for personal, non-commercial purposes only. Reproducing, distributing, or using the chatbot's responses for commercial gain without written permission is strictly prohibited.",
              ),
              SizedBox(height: 16),
              Text(
                "5. Limitation of Liability",
                style: TextStyle(fontSize: 15, fontWeight: FontWeight.bold),
              ),
              SizedBox(height: 8),
              Text(
                "We provide the chatbot “as is” without any warranties or guarantees. [Your Company/Name] shall not be held responsible for any damages—whether direct, indirect, incidental, or consequential—that result from the use or inability to use the chatbot. This includes but is not limited to loss of data, business interruption, or misinterpretation of information."
              ),
              SizedBox(height: 16),
              Text(
                "6. Changes to Terms",
                style: TextStyle(fontSize: 15, fontWeight: FontWeight.bold),
              ),
              SizedBox(height: 8),
              Text(
                "We reserve the right to update or modify these Terms and Conditions at any time. If changes are made, the updated version will be made available, and the date of the latest revision will be noted above. Continued use of the chatbot following any changes indicates your acceptance of the new terms."
              ),
              SizedBox(height: 16),
              Text(
                "7. Contact Us",
                style: TextStyle(fontSize: 15, fontWeight: FontWeight.bold),
              ),
              SizedBox(height: 8),
              Text(
                "If you have any questions or concerns about these Terms and Conditions or the chatbot in general, please reach out to us at [your contact email or support link]."
              ),
            ],
          ),
        ),
      ),
    );
  }
}
